version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    depends_on:
      - php
      - mysql
    networks:
      - laravel_network

  php:
    ports:
      - "5173:5173"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret$123147
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user1
      MYSQL_PASSWORD: laravel_password1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret$123147
    depends_on:
      - mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
